/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#feb300",
        "on-background": "#392e00",
        "tertiary-dim": "#005a53",
        "surface-variant": "#f5dc81",
        "surface-container": "#ffe796",
        "tertiary-container": "#81f3e5",
        "surface-dim": "#edd374",
        "on-surface": "#392e00",
        "inverse-on-surface": "#ae9c5e",
        "on-secondary-fixed-variant": "#972900",
        "outline-variant": "#bfac6c",
        "inverse-primary": "#feb300",
        "secondary-container": "#ffc4b3",
        "error-container": "#f95630",
        "surface-tint": "#7b5400",
        secondary: "#a83206",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#382400",
        error: "#b02500",
        "secondary-fixed-dim": "#ffb19a",
        surface: "#fff6e1",
        outline: "#86763b",
        "on-primary-fixed-variant": "#5e4000",
        "surface-bright": "#fff6e1",
        "on-surface-variant": "#695b23",
        "secondary-fixed": "#ffc4b3",
        "primary-dim": "#6b4900",
        "on-secondary-fixed": "#651900",
        "surface-container-highest": "#f5dc81",
        "on-tertiary-container": "#005a53",
        "on-error": "#ffefec",
        "inverse-surface": "#130e00",
        "primary-fixed-dim": "#eda600",
        "on-tertiary": "#bffff5",
        "tertiary-fixed-dim": "#72e4d7",
        "secondary-dim": "#952800",
        "on-primary-container": "#523700",
        "on-tertiary-fixed-variant": "#00655d",
        "surface-container-high": "#fae18c",
        primary: "#7b5400",
        "on-secondary-container": "#862400",
        tertiary: "#00675f",
        "on-tertiary-fixed": "#004640",
        "on-primary": "#fff1df",
        "tertiary-fixed": "#81f3e5",
        background: "#fff6e1",
        "surface-container-low": "#fff0c4",
        "on-error-container": "#520c00",
        "on-secondary": "#ffefeb",
        "error-dim": "#b92902",
        "primary-fixed": "#feb300",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        body: ["Be Vietnam Pro", "system-ui", "sans-serif"],
        label: ["Be Vietnam Pro", "system-ui", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 20px 40px -5px rgba(57, 46, 0, 0.06)",
        nav: "0 -20px 40px -5px rgba(0, 0, 0, 0.06)",
      },
    },
  },
  plugins: [],
};
